openapi: 3.1.0
info:
  title: API server for Six Cities
  description: Resources and routes list
  license:
      name: MIT
      url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
  - name: users
    description: Actions with users
  - name: offers
    description: Actions with offers
  - name: comments
    description: Actions with comments
paths:
  /users/register:
    post:
      tags:
        - users
      summary: register
      description: Registers new user
      requestBody:
        description: New user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: User with this email already registered
  /users/login:
    post:
      tags:
        - users
      summary: login
      description: Authorizes user by email and password
    get:
      tags:
        - users
      summary: auth status
      description: Returns user's authorization status
  /users/logout:
    post:
      tags:
        - users
      summary: logout
      description: Log out from user's account
  /users/favorites:
    get:
      tags:
        - users
      summary: favorite offers
      description: Returns user favorite offers
    patch:
      tags:
        - users
      summary: add to favorites
      description: Adds offer to user's favorites
    delete:
      tags:
        - users
      summary: remove from favorites
      description: Removes offer from user's favorites

components:
  schemas:
    createUser:
      type: object
      properties:
        name:
          type: string
          example: Keks Unknown
        email:
          type: string
          example: keks@htmlacademy.ru
        avatar:
          type: string
          example: placeholder.png
        password:
          type: string
          example: 123456
        type:
          type: string
          enum: ['обычный', 'pro']
          example: 'обычный'
    user:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea
        name:
          type: string
          example: Keks Unknown
        email:
          type: string
          example: keks@htmlacademy.ru
        avatar:
          type: string
          example: placeholder.png
        type:
          type: string
          enum: ['обычный', 'pro']
          example: 'обычный'
